# Statistical Software for Data Scientists

## Python - Tutorial 2 - NUMPY

### Exercise 1

1. Create 1D array t1 of 100 float values. Fill this array with random values in [-1.0, 1.0]

In [39]:
t1 = np.random.uniform(-1, 1, 100)
t1

array([ 5.30452112e-01,  6.06963079e-01,  4.66453461e-01,  1.44160457e-01,
       -9.96986811e-01,  9.24071212e-01,  4.98291690e-01, -3.91684384e-01,
        2.74717640e-03, -3.71081368e-01,  2.64081674e-02,  5.73141826e-02,
        3.04462333e-01, -3.86036605e-01, -9.26731396e-01, -9.32327146e-02,
       -2.65202019e-01,  6.01517414e-01, -3.70440750e-02,  7.56244764e-01,
       -6.59323205e-01, -9.63761403e-01,  8.18538434e-01, -5.80287438e-01,
        5.04035125e-01, -2.56112932e-01,  7.99160306e-01, -8.90410782e-01,
        5.52044367e-01,  5.81454258e-01, -8.64889558e-01, -2.51104682e-01,
        3.12855627e-01,  5.08403990e-01,  9.56801512e-01, -7.61412270e-01,
        1.73643454e-01,  5.15384931e-01,  9.35383931e-01, -3.41237490e-01,
        1.38098102e-01, -4.52341423e-01, -6.74107663e-01, -4.60779789e-01,
       -5.39668364e-01, -9.39695820e-01,  1.20991286e-01,  5.35538917e-01,
        1.56298927e-01, -4.69583221e-04, -7.32226307e-01,  8.26097458e-01,
       -7.53768177e-01,  

2. Calculate mean, median and standard deviation of t1

In [40]:
mean_t1 = np.mean(t1)
median_t1 = np.median(t1)
sd_t1 = np.std(t1)

print("Mean of t1:", mean_t1)
print("Median of t1:", median_t1)
print("Standard deviation of t1:", sd_t1)

Mean of t1: -0.041090752454301965
Median of t1: -0.018756829106408635
Standard deviation of t1: 0.5920860796252359


3. Create arrays t2 and t3 that contain respecfitvely positive and negative values from t1

In [41]:
# Positive of t1 in t2
t2 = np.array(t1[t1 > 0])
# Negative of t1 in t3
t3 = np.array(t1[t1 <= 0])

print(t2)
print()
print(t3)

[0.53045211 0.60696308 0.46645346 0.14416046 0.92407121 0.49829169
 0.00274718 0.02640817 0.05731418 0.30446233 0.60151741 0.75624476
 0.81853843 0.50403513 0.79916031 0.55204437 0.58145426 0.31285563
 0.50840399 0.95680151 0.17364345 0.51538493 0.93538393 0.1380981
 0.12099129 0.53553892 0.15629893 0.82609746 0.84660194 0.77086503
 0.14146592 0.98738919 0.20841943 0.2783343  0.48047963 0.29379704
 0.19154904 0.92420259 0.20083578 0.31195172 0.72744266 0.30581365
 0.86400042 0.00453181 0.25581475 0.88495111 0.76717667 0.58777588
 0.34730726]

[-9.96986811e-01 -3.91684384e-01 -3.71081368e-01 -3.86036605e-01
 -9.26731396e-01 -9.32327146e-02 -2.65202019e-01 -3.70440750e-02
 -6.59323205e-01 -9.63761403e-01 -5.80287438e-01 -2.56112932e-01
 -8.90410782e-01 -8.64889558e-01 -2.51104682e-01 -7.61412270e-01
 -3.41237490e-01 -4.52341423e-01 -6.74107663e-01 -4.60779789e-01
 -5.39668364e-01 -9.39695820e-01 -4.69583221e-04 -7.32226307e-01
 -7.53768177e-01 -2.68480308e-01 -8.75635838e-01 -7.16346428e

4. Create t4 by removing negative values from t1

In [42]:
t4 = np.delete(t1, np.argwhere(t1 < 0))
t4

array([0.53045211, 0.60696308, 0.46645346, 0.14416046, 0.92407121,
       0.49829169, 0.00274718, 0.02640817, 0.05731418, 0.30446233,
       0.60151741, 0.75624476, 0.81853843, 0.50403513, 0.79916031,
       0.55204437, 0.58145426, 0.31285563, 0.50840399, 0.95680151,
       0.17364345, 0.51538493, 0.93538393, 0.1380981 , 0.12099129,
       0.53553892, 0.15629893, 0.82609746, 0.84660194, 0.77086503,
       0.14146592, 0.98738919, 0.20841943, 0.2783343 , 0.48047963,
       0.29379704, 0.19154904, 0.92420259, 0.20083578, 0.31195172,
       0.72744266, 0.30581365, 0.86400042, 0.00453181, 0.25581475,
       0.88495111, 0.76717667, 0.58777588, 0.34730726])

5. Create t5 by replacing values in t1 that are greater than 0.5 with 1.0

In [43]:
t5 = np.where(
    t1 > 0.5,
    1.0,
    t1
)
t5

array([ 1.00000000e+00,  1.00000000e+00,  4.66453461e-01,  1.44160457e-01,
       -9.96986811e-01,  1.00000000e+00,  4.98291690e-01, -3.91684384e-01,
        2.74717640e-03, -3.71081368e-01,  2.64081674e-02,  5.73141826e-02,
        3.04462333e-01, -3.86036605e-01, -9.26731396e-01, -9.32327146e-02,
       -2.65202019e-01,  1.00000000e+00, -3.70440750e-02,  1.00000000e+00,
       -6.59323205e-01, -9.63761403e-01,  1.00000000e+00, -5.80287438e-01,
        1.00000000e+00, -2.56112932e-01,  1.00000000e+00, -8.90410782e-01,
        1.00000000e+00,  1.00000000e+00, -8.64889558e-01, -2.51104682e-01,
        3.12855627e-01,  1.00000000e+00,  1.00000000e+00, -7.61412270e-01,
        1.73643454e-01,  1.00000000e+00,  1.00000000e+00, -3.41237490e-01,
        1.38098102e-01, -4.52341423e-01, -6.74107663e-01, -4.60779789e-01,
       -5.39668364e-01, -9.39695820e-01,  1.20991286e-01,  1.00000000e+00,
        1.56298927e-01, -4.69583221e-04, -7.32226307e-01,  1.00000000e+00,
       -7.53768177e-01,  

6. Find max and min values of t1

In [44]:
max_t1 = np.max(t1)
min_t1 = np.min(t1)

print("Max value in t1: " ,  max_t1)
print("Max value in t1: ", min_t1)

Max value in t1:  0.9873891888543349
Max value in t1:  -0.9969868112180169


7. Reshape t1 as m1, 25x4 matrix

In [45]:
m1 = t1.reshape(25, 4)
m1

array([[ 5.30452112e-01,  6.06963079e-01,  4.66453461e-01,
         1.44160457e-01],
       [-9.96986811e-01,  9.24071212e-01,  4.98291690e-01,
        -3.91684384e-01],
       [ 2.74717640e-03, -3.71081368e-01,  2.64081674e-02,
         5.73141826e-02],
       [ 3.04462333e-01, -3.86036605e-01, -9.26731396e-01,
        -9.32327146e-02],
       [-2.65202019e-01,  6.01517414e-01, -3.70440750e-02,
         7.56244764e-01],
       [-6.59323205e-01, -9.63761403e-01,  8.18538434e-01,
        -5.80287438e-01],
       [ 5.04035125e-01, -2.56112932e-01,  7.99160306e-01,
        -8.90410782e-01],
       [ 5.52044367e-01,  5.81454258e-01, -8.64889558e-01,
        -2.51104682e-01],
       [ 3.12855627e-01,  5.08403990e-01,  9.56801512e-01,
        -7.61412270e-01],
       [ 1.73643454e-01,  5.15384931e-01,  9.35383931e-01,
        -3.41237490e-01],
       [ 1.38098102e-01, -4.52341423e-01, -6.74107663e-01,
        -4.60779789e-01],
       [-5.39668364e-01, -9.39695820e-01,  1.20991286e-01,
      

8. Compute mean values for each row then for each column

In [47]:
row_means = m1.mean(0)
col_means = m1.mean(1)

print("Mean values for each row: ", row_means)
print("Mean values for each column: ", col_means)

Mean values for each row:  [-0.14832241 -0.02977705  0.14814267 -0.13440622]
Mean values for each column:  [ 0.43700728  0.00842293 -0.07115296 -0.2753846   0.26387902 -0.3462084
  0.03916793  0.0043761   0.25416221  0.32079371 -0.36228269 -0.2057085
  0.06242512  0.14880462  0.11540967 -0.49772311 -0.08189476  0.17976944
 -0.28807923 -0.00653111 -0.57052796 -0.6220166   0.11457194  0.21843711
  0.13301402]


9. Replace randomly values in m1 with np.nan (create m2). Make sure that there is at least one NaN in each columnn.

In [54]:
import random

m2 = m1.copy()

for i in range(0, 30):
    # Generate random row index and col index
    random_row_index = random.randrange(0, np.size(m1, 0))
    random_col_index = random.randrange(0, np.size(m1, 1))
    # Set random element to NaN
    m2[random_row_index, random_col_index] = float('NaN')
    
np.isnan(m2[:, range(0, np.size(m1, 1))])

# We can see that each column has at least one True, so that one NaN

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [ True, False, False,  True],
       [False,  True, False,  True],
       [False,  True, False, False],
       [ True, False,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False,  True,  True]])

10. Count NaN values for each row then for each column

In [65]:
count_nan_rows = np.count_nonzero(np.isnan(m2), axis = 1)
count_nan_columns = np.count_nonzero(np.isnan(m2), axis = 0)

print(count_nan_rows)
print(count_nan_columns)

[0 0 1 2 2 1 3 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 1 1 2]
[6 5 4 7]


11. Compute mean value without NaNs of 1st column of m2. Replace NaNs in 1st column with mean value.

In [88]:
mean_value_col1 = np.nanmean(m2[:, 0])
print("Mean value of the first column in m2: ", mean_value_col1)

# Replace NaN values in the first column with the calculated mean 
# Find all NaN values in first column
m2_col1 = m2[:, 0]
m2_col1[np.argwhere(np.isnan(m2_col1))] = mean_value_col1
m2[:, 0] = m2_col1
m2

Mean value of the first column in m2:  -0.2764916777989334


array([[ 5.30452112e-01,  6.06963079e-01,  4.66453461e-01,
         1.44160457e-01],
       [-9.96986811e-01,  9.24071212e-01,  4.98291690e-01,
        -3.91684384e-01],
       [ 2.74717640e-03,             nan,  2.64081674e-02,
         5.73141826e-02],
       [-2.76491678e-01, -3.86036605e-01, -9.26731396e-01,
                    nan],
       [-2.65202019e-01,             nan, -3.70440750e-02,
                    nan],
       [-6.59323205e-01,             nan,  8.18538434e-01,
        -5.80287438e-01],
       [-2.76491678e-01, -2.56112932e-01,             nan,
                    nan],
       [-2.76491678e-01,  5.81454258e-01, -8.64889558e-01,
        -2.51104682e-01],
       [ 3.12855627e-01,  5.08403990e-01,  9.56801512e-01,
        -7.61412270e-01],
       [-2.76491678e-01,  5.15384931e-01,  9.35383931e-01,
        -3.41237490e-01],
       [ 1.38098102e-01, -4.52341423e-01, -6.74107663e-01,
        -4.60779789e-01],
       [-5.39668364e-01, -9.39695820e-01,  1.20991286e-01,
      

12. Create a function removeNaNs that, given a matrix mat and a column c, replaces NaNs in c with mean value of c

In [102]:
def removeNaNs(mat, c):
    # Compute mean value of c
    mean_value_c = np.nanmean(mat[:, c])
    # Replace NaN values by calculated mean
    col_c = mat[:, c]
    col_c[np.argwhere(np.isnan(col_c))] = mean_value_c
    mat[:, c] = col_c
    return mat

13. Apply removeNaNs for each column of m2

In [103]:
for index in range(np.size(m2, 1)):
    m2 = removeNaNs(m2, index)
    
m2

array([[ 5.30452112e-01,  6.06963079e-01,  4.66453461e-01,
         1.44160457e-01],
       [-2.83040626e-01, -2.83040626e-01, -2.83040626e-01,
        -2.83040626e-01],
       [-2.83040626e-01, -2.83040626e-01, -2.83040626e-01,
        -2.83040626e-01],
       [-2.76491678e-01, -3.86036605e-01, -9.26731396e-01,
        -2.95913462e-01],
       [-2.65202019e-01, -9.83423585e-02, -3.70440750e-02,
        -2.95913462e-01],
       [-6.59323205e-01, -9.83423585e-02,  8.18538434e-01,
        -5.80287438e-01],
       [-2.76491678e-01, -2.56112932e-01,  1.41483402e-02,
        -2.95913462e-01],
       [-2.76491678e-01,  5.81454258e-01, -8.64889558e-01,
        -2.51104682e-01],
       [ 3.12855627e-01,  5.08403990e-01,  9.56801512e-01,
        -7.61412270e-01],
       [-2.76491678e-01,  5.15384931e-01,  9.35383931e-01,
        -3.41237490e-01],
       [ 1.38098102e-01, -4.52341423e-01, -6.74107663e-01,
        -4.60779789e-01],
       [-5.39668364e-01, -9.39695820e-01,  1.20991286e-01,
      

14. Find max value for each col of m1

In [117]:
max_each_col = np.min(m1, 0)
max_each_col

array([-0.99698681, -0.9637614 , -0.9267314 , -0.93031608])

15. Find min value for each row of m1

In [118]:
min_each_row = np.min(m1, 1)
min_each_row

array([ 0.14416046, -0.99698681, -0.37108137, -0.9267314 , -0.26520202,
       -0.9637614 , -0.89041078, -0.86488956, -0.76141227, -0.34123749,
       -0.67410766, -0.93969582, -0.73222631, -0.75376818, -0.87563584,
       -0.77996973, -0.93031608, -0.59750964, -0.81011968, -0.61620652,
       -0.96521129, -0.90657373, -0.66605921, -0.55867841, -0.36590409])

---

### Exercise 2

1. Create a 10x6 2D array m filled with random integers in [0, 10]

In [126]:
m = np.random.randint(0, 10, 60)
m = m.reshape(10, 6)
m

array([[4, 4, 2, 7, 1, 2],
       [4, 4, 1, 4, 4, 7],
       [9, 3, 2, 9, 1, 0],
       [4, 8, 5, 2, 0, 8],
       [4, 4, 6, 7, 9, 8],
       [7, 3, 6, 2, 2, 5],
       [6, 7, 4, 0, 2, 8],
       [0, 4, 3, 0, 9, 4],
       [4, 2, 0, 1, 8, 1],
       [6, 5, 5, 7, 6, 6]])

2. Create the function that computes the counts of unique values row-wise. Output is 10x11 matrix where columns represent numbers from 0 to 10. The values are the counts of the numbers in the respective rows.

In [161]:
def countValuesRowWise(matrix):
    countMatrix = np.zeros((10, 11))
    # Iterate through each row of the matrix
    # at each element, add +1 to its respective position in countMatrix
    countMatrix[0:] = range(0, 11)
    for i in range(1, np.size(matrix, 0)):
        for j in range(0, np.size(matrix, 1)):
            element = matrix[i, j]
            countMatrix[i, element] = countMatrix[i, element] + 1
    return countMatrix

countValuesRowWise(m)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 0.,  2.,  2.,  3.,  8.,  5.,  6.,  8.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  4.,  5.,  6.,  7.,  8., 11., 10.],
       [ 1.,  1.,  3.,  3.,  5.,  6.,  6.,  7., 10.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  6.,  5.,  7.,  8.,  9., 10., 10.],
       [ 0.,  1.,  4.,  4.,  4.,  6.,  7.,  8.,  8.,  9., 10.],
       [ 1.,  1.,  3.,  3.,  5.,  5.,  7.,  8.,  9.,  9., 10.],
       [ 2.,  1.,  2.,  4.,  6.,  5.,  6.,  7.,  8., 10., 10.],
       [ 1.,  3.,  3.,  3.,  5.,  5.,  6.,  7.,  9.,  9., 10.],
       [ 0.,  1.,  2.,  3.,  4.,  7.,  9.,  8.,  8.,  9., 10.]])

---

### Exercise 3

1. Import iris dataset keeping the text intact as a 2D array named irisdata

In [170]:
irisdata = np.genfromtxt("iris_data.csv", delimiter = ',', dtype=object)
irisdata

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

The columns are respectively:
* sepal length
* sepal width
* petal length
* petal width
* species

2. Extract from irisdata the species column as an array of string named species

In [173]:
species = np.array(irisdata[:, -1])
species

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicol

3. Extract from irisdata sepal length column as an array of float values

In [175]:
sepal_length = np.array(irisdata[:,0])
sepal_length

array([b'5.1', b'4.9', b'4.7', b'4.6', b'5.0', b'5.4', b'4.6', b'5.0',
       b'4.4', b'4.9', b'5.4', b'4.8', b'4.8', b'4.3', b'5.8', b'5.7',
       b'5.4', b'5.1', b'5.7', b'5.1', b'5.4', b'5.1', b'4.6', b'5.1',
       b'4.8', b'5.0', b'5.0', b'5.2', b'5.2', b'4.7', b'4.8', b'5.4',
       b'5.2', b'5.5', b'4.9', b'5.0', b'5.5', b'4.9', b'4.4', b'5.1',
       b'5.0', b'4.5', b'4.4', b'5.0', b'5.1', b'4.8', b'5.1', b'4.6',
       b'5.3', b'5.0', b'7.0', b'6.4', b'6.9', b'5.5', b'6.5', b'5.7',
       b'6.3', b'4.9', b'6.6', b'5.2', b'5.0', b'5.9', b'6.0', b'6.1',
       b'5.6', b'6.7', b'5.6', b'5.8', b'6.2', b'5.6', b'5.9', b'6.1',
       b'6.3', b'6.1', b'6.4', b'6.6', b'6.8', b'6.7', b'6.0', b'5.7',
       b'5.5', b'5.5', b'5.8', b'6.0', b'5.4', b'6.0', b'6.7', b'6.3',
       b'5.6', b'5.5', b'5.5', b'6.1', b'5.8', b'5.0', b'5.6', b'5.7',
       b'5.7', b'6.2', b'5.1', b'5.7', b'6.3', b'5.8', b'7.1', b'6.3',
       b'6.5', b'7.6', b'4.9', b'7.3', b'6.7', b'7.2', b'6.5', b'6.4',
      

4. Change the type of irisdata 1st to 4th colum to float and last one to string

In [178]:
for i in range(0, 4):
    irisdata[:, i] = (irisdata[:, i]).astype("float64")
    
irisdata[:, -1] = (irisdata[:, i]).astype("str")

5. Find the mean, median, standard deviation of iris's sepal length (1st column)

In [183]:
sepal_length = irisdata[:, 0]
mean_sepal_length = np.mean(sepal_length)
median_sepal_length = np.median(sepal_length)
sd_sepal_length = np.std(sepal_length)

print("Mean of sepal length: ", mean_sepal_length)
print("Median of sepal length: ", median_sepal_length)
print("Standard deviation of sepal length: ", sd_sepal_length)

Mean of sepal length:  5.843333333333335
Median of sepal length:  5.8
Standard deviation of sepal length:  0.8253012917851409


6. Normalize the values of iris' petal length

Remember that the normalized value of ${x}$ with mean ${\mu}$ and variance ${\sigma}$ is:

${normalized(x) = \frac{x - \mu}{\sigma} }$

In [185]:
petal_length = irisdata[:, 2]
mean_petal_length = np.mean(petal_length)
sd_petal_length = np.std(petal_length)
variance_petal_length = np.sqrt(sd_petal_length)

normalized_petal_length = (petal_length - mean_petal_length) / variance_petal_length
normalized_petal_length

array([-1.7786552538440004, -1.7786552538440004, -1.8540646060420218,
       -1.7032459016459789, -1.7786552538440004, -1.552427197249936,
       -1.7786552538440004, -1.7032459016459789, -1.7786552538440004,
       -1.7032459016459789, -1.7032459016459789, -1.6278365494479574,
       -1.7786552538440004, -2.0048833104380646, -1.9294739582400429,
       -1.7032459016459789, -1.8540646060420218, -1.7786552538440004,
       -1.552427197249936, -1.7032459016459789, -1.552427197249936,
       -1.7032459016459789, -2.080292662636086, -1.552427197249936,
       -1.4016084928538932, -1.6278365494479574, -1.6278365494479574,
       -1.7032459016459789, -1.7786552538440004, -1.6278365494479574,
       -1.6278365494479574, -1.7032459016459789, -1.7032459016459789,
       -1.7786552538440004, -1.7032459016459789, -1.9294739582400429,
       -1.8540646060420218, -1.7032459016459789, -1.8540646060420218,
       -1.7032459016459789, -1.8540646060420218, -1.8540646060420218,
       -1.854064606042021

7. Create function that normalize values in any column of an array